POST http://localhost:3003/api/products/new
Content-Type: application/json

{
    "name": "MSI MAG FORGE M100R Cristal Templado USB 3.2 ARGB Negra",
    "category": "Case",
    "price":48,
    "deal":true,
    "dealPrice":63
}